---
title: L.P.I.F. Charity Drives
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
root:
- |
  .
  ├── Home.md    # => http://example.com/about.html
  ├── index.html    # => http://example.com/
  └── contact.html  # => http://example.com/contact.html
  .
  ├── about.md          # => http://example.com/about.html
  ├── documentation     # folder containing pages
  │   └── doc1.md       # => http://example.com/documentation/doc1.html
  ├── design            # folder containing pages
  │   └── draft.md      # => http://example.com/design/draft.html
- - 
